Issue #143 - Default permission on install and save
backdrop-contrib/paragraphs pull request #151
Opened 2022-12-06 14:50 UTC by yorkshire-pudding

Fixes #143

2022-12-20 02:11 UTC, laryn commented
@yorkshire-pudding Does this PR overwrite permissions for existing Paragraphs types, or just provide defaults for new Paragraphs types? If the former that may be problematic in the case that someone has configured their Paragraphs type differently than these defaults, and then the permissions get overwritten by a default setting. (I haven't tested yet but I'm wondering about the changes in the install file.)

2023-01-23 00:19 UTC, laryn requested changes
@yorkshire-pudding I think it's looking great. In the meantime however we have a new core permissions filter that should simplify a lot of this code. I think we can strip out a lot and just build this URL when needed (e.g. when the user has permission to modify permissions):

```
admin/config/people/permissions?search=paragraphs%20type%20permissions
```

2023-01-23 00:19 UTC, laryn commented on modules/paragraphs_bundle_permissions/paragraphs_bundle_permissions.install
> +      '@url' => paragraphs_bundle_permissions_url(),
Can we use the basic permissions page URL and add a query on this link to take advantage of the new permissions filter? 
e.g. build this URL: `admin/config/people/permissions?search=paragraphs`

Then we might not need the special function at all. This link/portion of the message should only show if the user has permission to update permissions.

2023-01-23 00:19 UTC, laryn commented on paragraphs.admin.inc
> +      $url_base = 'admin/config/people/permissions';
This section should be simplified/reworked to use the core permissions filter as well.

2023-01-31 17:43 UTC, laryn commented on paragraphs.admin.inc
> +      $url_base = 'admin/config/people/permissions';
@yorkshire-pudding If we do end up keeping `paragraphs_bundle_permissions_url` can we use it here as well?

2023-02-10 05:03 UTC, laryn commented
@yorkshire-pudding Two thoughts I'd love to hear your perspective on:

1) I think we need to use something like `$admin_role = config_get('system.core', 'user_admin_role');` rather than assuming `administrator` as the role.

2) We're using the same logic structures and strings multiple times for the conditional messages, etc. Is there any way to simplify that in a reasonable way to reduce redundancy?

2023-02-10 10:18 UTC, yorkshire-pudding commented
> @yorkshire-pudding Two thoughts I'd love to hear your perspective on:
> 
> 1. I think we need to use something like `$admin_role = config_get('system.core', 'user_admin_role');` rather than assuming `administrator` as the role.
> 2. We're using the same logic structures and strings multiple times for the conditional messages, etc. Is there any way to simplify that in a reasonable way to reduce redundancy?

Thanks for these suggestions @laryn - I hadn't considered the first one but of course, people can choose which role gets the new admin permissions.
Regarding the second, yes, that component does make sense to put into a shared function.  Two points to note:
- I've used `get_t()` so it will work with `hook_install`
- I've kept the separate `paragraphs_bundle_permissions_url()` function as this is called without a message from the Operations menu on the Paragraphs Overview page.

2023-02-25 23:00 UTC, merged

2023-02-25 23:00 UTC, laryn commented
Thanks for your persistence and patience @yorkshire-pudding! Merged.